trigger:
- main


pool:
  vmImage: windows-latest

stages:
  - stage: config_environment
    displayName: config environment stage
    jobs:
      - job: config_environment_job1
        steps:
          - script: echo config_environment_job1 run
            displayName: run script in one line

          - script: |
              echo config_environment_job1 run
              echo config_environment_job1 run again
            displayName: run script in multiple line

          - task: CopyFiles@2
            inputs:
              Contents: '**'
              TargetFolder: 'c:\temp'

      - job: finish_config_environment_job1
        dependsOn: config_environment_job1
        condition: succeeded()
        steps:
          - script: echo finsih finish_config_environment_job1
        
      - job: RunsInContainer
        pool:
          vmImage: ubuntu-latest
        container: ubuntu:latest
        dependsOn: []
        steps:
          - script: echo run in container
        
      - job: RunsInNewPool
        pool:
          vimage: ubuntu-latest
        dependsOn: []
        steps:
          - script: echo run in new pool

      - job: test_different_data_to_repeat_job
        strategy:
          matrix:
            Python35:
              PYTHON_VERSION: '3.5.10'
            Python36:
              PYTHON_VERSION: '3.6.13'
            Python37:
              PYTHON_VERSION: '3.8.10'
          maxParallel: 2
          
        pool:
          vimage: ubuntu-latest
        dependsOn: []
        steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(python.version)'
          displayName: 'Use Python $(python.version)'
        - script: python -V


  - stage: run_script
    displayName: run script stage
    dependsOn: config_environment
    condition: succeeded('config_environment')
    jobs:
      - job: run_script_job
        steps:
          - script: echo run_script
  
