trigger:
- main


pool:
  vmImage: windows-latest

stages:
  - stage: config_environment
    displayName: config environment stage
    jobs:
      - job: config_environment_job1
        steps:
          - script: echo config_environment_job1 run
            displayName: run script in one line

          - script: |
              echo config_environment_job1 run
              echo config_environment_job1 run again
            displayName: run script in multiple line

          - task: CopyFiles@2
            inputs:
              Contents: '**'
              TargetFolder: 'c:\temp'

      - job: finish_config_environment_job1
        dependsOn: config_environment_job1
        condition: succeeded()
        steps:
          - script: echo finsih finish_config_environment_job1
        
      - job: RunsInContainer
        container: ubuntu:latest
        dependsOn: []
        steps:
          - script: echo run in container
        
      - job: RunsInNewPool
        pool:
          vimage: ubuntu-latest
        dependsOn: []
        steps:
          - script: echo run in new pool



  - stage: run_script
    displayName: run script stage
    dependsOn: config_environment
    condition: succeeded('config_environment')
    jobs:
      - job: run_script_job
        steps:
          - script: echo run_script
  
