trigger:
- main
pr:
- main

variables:
  buildTimeStamp: # will be set by script

pool:
  vmImage: windows-latest

stages:
  - stage: build
    displayName: build package
    jobs:
      - job: config_and_build
        steps:
        
          - task: PowerShell@2
            displayName: set variable buildTimeStamp
            inputs:
              targetType: 'inline'
              script: |
                $date=$(Get-Date -Format yyyy-MM-dd_HH.mm);
                Write-Host "##vso[task.setvariable variable=buildTimeStamp]$date"

          - script: |
              echo $(buildTimeStamp)
            displayName: show buildTimeStamp
                        
          - script: |
              pip install -r requirement.txt
            displayName: config_env



          - script: |
              pyinstaller -F run.py
            displayName: build_package


          - script: |
              mkdir package_manual
              move dist\run.exe  package_manual/
            displayName: prepare_artfact

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: package_manual
              ArtifactName: $(buildTimeStamp)
              publishLocation: 'Container'
                    
          - script: |
              set
            displayName: show_env

