trigger:
- main
pr:
- main

variables:
- name: artfact_name
  value: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: windows-latest

stages:
  - stage: build
    displayName: build package
    jobs:
      - job: config_and_build
        steps:
          - script: |
              pip install -r requirement.txt
            displayName: config_env

          - script: |
              echo $(artfact_name)
            displayName: show artfact name

          - script: |
              pyinstaller -F run.py
            displayName: build_package

          - script: |
              mkdir package_manual
              move dist\run.exe  package_manual/
            displayName: prepare_artfact
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: package_manual
              ArtifactName: $(artfact_name)
              publishLocation: 'Container'
                    
          - script: |
              set
            displayName: show_env

